### PR TITLE
Various pAI Fixes

### LINKED ISSUE #16277: [Bug]: The pAI "Records" program is undownloadable
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

You can't download the records program available to pAI's on their computer interface. Clicking the button does nothing.

### How to reproduce

_No response_

### Round ID

_No response_

### Staff ckey

_No response_

### LINKED ISSUE #16840: [Bug]: A lot of pAI PDA programs lead to 'Interface  was not found' and softlocking it
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Title

### How to reproduce

_No response_

### Round ID

_No response_

### Staff ckey

_No response_

### LINKED ISSUE #16908: [Bug]: PAI Bug for Software System (Medical hud)
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When joining as a PAI. i downloaded a few systems as you do and opened the Medi Hud because i was with a paramedic. I selected it and nothing happened so i tried to exit out. But i couldnt exit out of that tab. Thusly i can no longer access anything computer wise. Which is pretty bad.

### How to reproduce

Become PAI
Download Medical Hud
Open Medical Hud
Get stuck in the medi hud.

I reconnected, Quit out and rejoined, And cleared cache and rejoined 

### Round ID

co3-acyf

### Staff ckey

_No response_

### LINKED ISSUE #17064: [Bug]:  pAI issues compilation [Softlock + other errors: !!Read before submitting your own pAI bug!! broken interfaces]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] I have done all that I can on my end to try to resolve these issues including working with my cache, etc.
- [X] I can confirm this is a long term and consistent issue.
- [X] I can confirm that multiple people have experienced such issues.

### Location

Horizon

### Describe the issue

I will be including my main three bugs here which have not been reported as well as another bug that I noticed and was going to report myself, but other folks have been multi-reporting - hopefully this keyword search will keep folks from being able to miss the previous posts including this one. pAI softlock broken computer interface. There.
‏‏‎ ‎
‏‏‎ ‎
‏‏‎ ‎
Issue 1. 
**When becoming a pAI, it does not automatically update out of ghost mode** and seems to believe that I am still a ghost.

Steps to reproduce:
1. Submit pAI personality
2. Get accepted as pAI personality

Tada! You are now a ghost that registers as a pAI.

3. Reconnect, to update your tabs so that you have pAI functionality. 
4. Get added to a local computer such as a PDA or wristbound.
5. attempt to open local computer.

Temporary workaround and problems with it:
I can try to reconnect, and that usually updates the tabs to include pAI tabs, but this unfortunately keeps me from being able to use any local computer system. When trying to do so, it is broken and refuses to open without any error messages.
‏‏‎ ‎‎
‎‏‏‎ ‎ghost pai
‎‏‏‎ ‎
Issue 2. 
**When using a pAI computer interface, if I am disconnected, I fail to be able to open my computer interface again**. It is broken and refuses to open without any error messages sent. (This does not refer to local computer such as a PDA - I cannot in any way access those anyway, see Issue 1).

Steps to reproduce:
1. Submit pAI personality
2. Get accepted as pAI personality
6. Open computer interface, use it
7. Crash / disconnect. Sometimes the bug happens if the computer interface is open, sometimes when it is closed too, but more often when it's still open on disconnect/crash.
8. Reconnect and attempt to open interface.

There is no workaround for this. Attempting to refresh tgui, reconnect again, etc, nothing works.

‎‏‏‎ ‎
‎‏‏‎ ‎
Issue 3:

Previously, I was able to access various radio types as a pAI. I can no longer do this. Attempting to speak on the Security channel to assist my user does not work and simply turns the message into a simple say. It is frustrating as there is information I need to report occasionally that I cannot do privately to security as a result of this. However, I am still capable of hearing Security chatter, as my user is a security officer. This is rough.
‎‏‏‎ ‎
‎‏‏‎ ‎
‎‏‏‎ ‎
Issue 4: 
**When using a pAI computer interface, duplicate entries of certain downloaded software will appear** in the top half of the software list, while also appearing in the bottom category for software at the same time. **Clicking on any of these 'trap' duplicates in the top half of the software list will softlock the computer interface completely**. The entries for these softwares that show up in the bottom still work. Software that doesn't have a duplicate but appears in the top (such as doorjack) is still functional.

Steps to reproduce:
1. Submit pAI personality
2. Get accepted as pAI personality
4. Open computer interface
6. Download, for instance, security/medical HUD
7. Notice the two entries for them, one above and one below the separation of software types
8. Click on the duplicated program above the separation of software programs
9. You are now softlocked

There is no workaround for this. Attempting to refresh tgui, reconnect, etc, nothing works. This is the issue that has been reported multiple times, my main goal is to simply report the additional bugs I've experienced, and help organize the multiple pAI bugs I've experienced and potentially help make it harder for folks to unintentionally miss the fact that they've already been reported.
‏‏‎ ‎
‏‏‎ ‎pai softlock options
‏‏‎ 
The red-outlined options here are traps that will softlock my pAI computer interface.‎

### Round ID

Every round I've been in in the last two weeks.

### PR DESCRIPTION
**Pull request by AlaunusLux**
A collection of bug fixes for pAIs! Hopefully it will be less painful now :)

My main concern is the change of the procs to verbs. It makes the init_verbs() proc able to give the pAI their proper verbs and tabs without a relog, and all works well for my pAI testing, but I'm not sure of the difference from a technical point - will this have repercussions?

Also, I had to manually add pai/logout.dm to the .dme, is this usual?

- pAI now have the ghost tab removed, and proper verbs and tabs added upon spawning, without having to relog. 
- pAI can now access PDA and Computers they are inserted into. 
- Programs that would softlock the pAI computer interface (those without an ID) are removed from the Programs list
- pAI UI windows that were open when closing the client are now possible to re-open
- Adds error message when trying to download incompatible software.

Fixes #17064
Fixes #16908 (duplicate)
Fixes #16840 (duplicate)

Fixes #16277

### CODE REVIEW

**Comment by AlaunusLux** [comment]
!bugfix

File: tgui/packages/tgui/routes.tsx [hunk 1]
```diff
@@ -16,8 +16,8 @@ const requireInterface = require.context('./interfaces');
 const routingError =
   (type: 'notFound' | 'missingExport', name: string) => () => {
     return (
-      <Window>
```
Comment (NonQueueingMatt) [inline tgui/packages/tgui/routes.tsx:19]: Don't touch this file.

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/routes.tsx (hunk 1 above)
Comment (AlaunusLux) [reply tgui/packages/tgui/routes.tsx:19]: Why? It locks people out of UIs the way it is. If it's used for non-computer UIs or otherwise incompatible in certain situations, then what's the solution for locking people out of their UIs when they reach this screen?

Comment (AlaunusLux) [reply tgui/packages/tgui/routes.tsx:19]: For clarity, this is what the pages looks like currently- it locks your device. Closing and reopening it shows the same page, with no way to navigate back to the programs page. The only fix is the pAI owner wiping the pAI and redownloading.

image


With NtosWindow:

image


Given, the other changes to hide programs without IDs stops this from being a problem for pAIs, I was just trying to be proactive to prevent it from happening in the future, or with the missingExport flag.

Comment (NonQueueingMatt) [reply tgui/packages/tgui/routes.tsx:19]: Because that file is for all UIs - we don't want all UIs to be NTOSWindows. 

The problem you're describing above is just that the pAI Flashlight shouldn't open at all because it's a service - you shouldn't be editing general functionality to fix it.

**Comment by NonQueueingMatt** [comment]
!review

File: tgui/packages/tgui/routes.tsx (hunk 1 above)
Comment (AlaunusLux) [reply tgui/packages/tgui/routes.tsx:19]: I was not editing general UI functionality for the pAI flashlight - I was editing it for other places where the same might occur and lock a device.

Ideally we would add proper routing for NtosWindow error pages, but as this PR is pAI focused and the problem is solved another way, I'll leave this page be and track the issue in a bug report.

File: code/modules/modular_computers/computers/modular_computer/ui.dm [hunk 2]
```diff
@@ -180,8 +180,11 @@
 			register_account()
 		. = TRUE
 	if(action == "PC_toggleservice")
-		toggle_service(params["service_to_toggle"], usr)
-		. = TRUE
+		if(params["service_to_toggle"] == "pai_access_lock" && istype(usr, /mob/living/silicon/pai))
+			usr.show_message(SPAN_WARNING("Access denied."))
```
Comment (NonQueueingMatt) [inline code/modules/modular_computers/computers/modular_computer/ui.dm:184]: to_chat()

File: code/modules/tgui/states/default.dm [hunk 3]
```diff
@@ -47,8 +47,15 @@ var/global/datum/ui_state/default/default_state = new
...
 		return UI_INTERACTIVE
-	else
-		return min(..(), UI_UPDATE)
+	else if(src_object == src.parent_computer)
+		if(istype(src_object, /obj/item/modular_computer))
+			var/obj/item/modular_computer/PDA = src_object
+			if(PDA.pAI_lock == FALSE)
+				return UI_INTERACTIVE
+			else
+				src.show_message(SPAN_WARNING("Access denied."))
```
Comment (NonQueueingMatt) [inline code/modules/tgui/states/default.dm:59]: to_chat

**Review by NonQueueingMatt — CHANGES_REQUESTED** [review]

**Review by NonQueueingMatt — APPROVED** [review]
